server:
  port: 8003 # 服务端口

spring:
  application:
    name: service-oss # 服务名
  profiles:
    active: dev # 环境设置:dev、test、prod

# 阿里云 OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4G63B2WuUUu7AwPZS210X
      keysecret: YdwJVa3cZeVi76icf4mnhAe9yL8fci----无效的
      bucketname: owhush96--无效的